### ISSUE TITLE
Better configurable greeting message

### ISSUE THREAD

**Issue by Naxos84** [XtremeOwnage/WarBot#45]
**Describe the solution you'd like**
When I'm configuring the greeting message via "bot, enable greeting #CHANNELNAME MESSAGE" I like to specify where the @Username is positioned.

i.e

bot, enabled greeting #MyWelcomeChannel Hello and welcome to my server

this would produce something like:
$USER$, Hello and welcome to my server

but i like something like:

Hello $USER$ and welcome to my server

If the user placeholder (in the above case it is $USER$) is not present than use the current solution.
So that the currently set message will not break.

**Comment by XtremeOwnageDotCom** [comment]
Templated messages will be enabled for both user join, and user leave messages.

The updates are being currently tested in DEVL, and will be rolled out to production today or tomorrow.

The guild setup dialog has been updated to account for the new changes as well.

The token will be {User}

**Comment by XtremeOwnageDotCom** [comment]
Implemented in production!
