### ISSUE TITLE
War alerts set to off

### ISSUE THREAD

**Issue by Spinolli** [XtremeOwnage/WarBot#48]
Hey your war alerts are automatically set to false you have to manually set them on even after setup.

**Comment by XtremeOwnageDotCom** [comment]
Bug confirmed, a fix will be rolled out with today's release.

**Comment by XtremeOwnageDotCom** [comment]
This issue is being resolved. The defaults are now to enable, AND, the setup dialog will now prompt the user to configure the individual war notifications.

**Comment by XtremeOwnageDotCom** [comment]
New release will be rolled out soon.

**Comment by Spinolli** [comment]
Fantastic, thanks all.
