### ISSUE TITLE
Add reminder to start war

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [XtremeOwnage/WarBot#52]
Add reminder to start the next war, sometime after the war started.

**Comment by louloute88** [comment]
la guerre de clan commence veuillez vous placez### 

> _****_

**Comment by louloute88** [comment]
> Ajoutez un rappel pour commencer la prochaine guerre, quelque temps après le début de la guerre.

> 9H 

> 15H 

> 21H 

> 03H

**Comment by XtremeOwnageDotCom** [comment]
Added the ability to create a discord event two hours before the prep period starts. This fills the need, I think.
