### ISSUE TITLE
Clear message behaviour 

### ISSUE THREAD

**Issue by HarbingerNight** [XtremeOwnage/WarBot#77]
Came here specifically for this issue #49 #69 ( actually expedition ) noticed there seems to be a permission option in integrations but not a slash for it.

Specifically would like the bot to be able to delete each notice after a set duration has past from when that message is posted ( war and expo ) vs. Setting a specific clear time where it clears all messages from the channel.

I don't think the thread per war idea is going to work well. Discord has apparently put a limit on active threads and creating a new thread per war seems like overhead overkill and would probably hit that limit or eventually cause them to implement some kinda rate limit against it 

- ManDrako ( Hustle Prime Admin )

**Comment by XtremeOwnageDotCom** [comment]
Hunh,

I like the idea of a set timer for deleting messages. Would actually be pretty easy to implement as well, and would be easy on resources.

The idea of using threads actually would be quite a bit more work anyways. 

In either case, a few people have been asking for this feature back, its next up on my list.

**Comment by XtremeOwnageDotCom** [comment]
@HarbingerNight 

Changes are live in DEV: https://docs.warbot.dev/Changelogs/v4.0/v4.1.4/

**Comment by XtremeOwnageDotCom** [comment]
Changes have been published to production.

Changelogs: https://docs.warbot.dev/Changelogs/v4.0/v4.2/

Let me know if you have any issues with this, or, if you would like any additional features or functionality. Feel free to reopen this ticket if the feature does not work as expected.
