### ISSUE TITLE
Configure Message Clearing via Commands

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [XtremeOwnage/WarBot#78]
Implement commands to allow configuring messaging clearing functionality.

**Comment by XtremeOwnageDotCom** [comment]
Implemented in version 4.2.1 for wars and expeditions. Still need to implement for portal.

**Comment by HarbingerNight** [comment]
Not appearing in production yet. Possibly just need to wait for discord to cache up. But can you check you pushed the application commands to gateway?

**Comment by XtremeOwnageDotCom** [comment]
@HarbingerNight  version 4.2.1 is running in dev. Version 4.2 is running in prod. (Doesn't have those commands, yet)

**Comment by XtremeOwnageDotCom** [comment]
But, you can configure the message clearing via https://warbot.dev/ in prod.

**Comment by XtremeOwnageDotCom** [comment]
`/portal clear` command added in version 4.2.2. (Not yet released)

**Comment by XtremeOwnageDotCom** [comment]
Going to guess, this issue was resolved/implemented two years ago, as it is currently available.
