### ISSUE TITLE
Channel Loading

### ISSUE THREAD

**Issue by HarbingerNight** [XtremeOwnage/WarBot#81]
**Describe the bug**
The website seems to have an issue w/ loading the channels on the Hustle Castle Settings. Just sits there. Needs a more efficient method such as caching the channels and just having the person do a refresh if the one they want isn't there.

Desktop (please complete the following information):

OS: Ubuntu 22.04 WSL 2 on Windows 10
Browser: NA
Version:
Smartphone (please complete the following information):

Device: Huawei M5
OS: Android 8.0
Browser:
Chrome
Termius SSL
Microsoft RD Client

**Comment by XtremeOwnageDotCom** [comment]
I actually did add caching back in #60 

For some-odd reason, discord is dirt-slow to return the list of channels for a guild. As such, the current functionality caches the channels, after they have been loaded once. So, the first query takes a while, but, after that, it's all cached unless you hit refresh.

I would, however, like to improve on this, as its still certainly not ideal.
